language: cpp

git:
  depth: 3

addons:
  apt:
    packages:
    - python3

matrix:
  include:
    - name: "Visual Studio 2017"
      os: windows
      before_script:
        - choco install python3

    - name: "Linux clang"
      os: linux
      compiler: clang

script:
  - mkdir build && cd build
  - cmake $CMAKE_FLAGS -DKYTE_TESTS=ON ..
  - cmake --build .
  - ctest
