language: cpp
os: windows

git:
  depth: 3

before_script:
  - choco install python --version 3.8.0

script:
  - mkdir build && cd build
  - cmake $CMAKE_FLAGS -DKYTE_TESTS=ON -DPYTHON_EXECUTABLE=/c/Python38/python.exe ..
  - cmake --build .
  - ctest
